basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a swagger documentation for Product Service.
  title: Product Service
  version: "1.0"
paths: {}
schemes:
- http
- https
swagger: "2.0"
